# Generated by Django 5.0.1 on 2024-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_converted_date_lead_date_added_lead_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
